version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - export SONAR_TOKEN=6ec343e563cb7aa55def37958b3b7a29dfe3c1f9
      - echo Build started on `date`
      - mvn test sonar:sonar
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - mv target/cloud-url-shortner-0.0.1-SNAPSHOT.jar .
artifacts:
  files:
    - cloud-url-shortner-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - url-shortner-scripts/*
