server:
  port: 8080
neurl:
  api:
    longUrlMaxSize: 2097152

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: /ping
spring:
  datasource:
    url: jdbc:mysql://loyaltyreward.chwlezgyi7rm.eu-west-1.rds.amazonaws.com:3306/LoyaltyReward
    username: loyaltydb
    password: loyaltydb
    driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: update
